name: Build Images

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
      paths:
        - docker-compose.yml
        - services

jobs:
  build:
    strategy:
      matrix:
        profile:
          - auto
          - invoke
          - comfy
          - download
    runs-on: ubuntu-latest
    name: ${{ matrix.profile }}
    steps:
      - uses: actions/checkout@v3

     # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule,pattern=nightly-{{date 'YYYYMMDDhhmmss'}}
            type=schedule,pattern=latest
            type=sha,format=short

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      # build images      
      - name: build with  Docker Compose
        run: docker compose --profile ${{ matrix.profile }}  build --progress plain
        env:
          AUTO_IMAGE_URL: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: docker push image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
       