name: Build Images

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
      paths:
        - docker-compose.yml
        - services

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: registry.us-west-1.aliyuncs.com
  # github.repository as <account>/<repo>
  AUTO_IMAGE_NAME: roweb/automatic1111-sd-webui

jobs:
  build:
    strategy:
      matrix:
        profile:
          - auto
          # - invoke
          # - comfy
          # - download
    runs-on: ubuntu-latest
    name: ${{ matrix.profile }}
    steps:
      - uses: actions/checkout@v3

     # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.AUTO_IMAGE_NAME }}:latest
          tags: |
            type=schedule,pattern=nightly-{{date 'YYYYMMDDhhmmss'}}
            type=schedule,pattern=latest
            type=sha,format=short

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image ${{ env.REGISTRY }}/${{ env.AUTO_IMAGE_NAME }}:latest
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: ./services/AUTOMATIC1111/
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # # build images      
      # - name: build with  Docker Compose
      #   if: ${{ matrix.profile }} == 'auto'
      #   run: docker compose --profile ${{ matrix.profile }}  build --build-arg AUTO_IMAGE_URL=${{ env.REGISTRY }}/${{ env.AUTO_IMAGE_NAME }}:latest --progress plain
      
      # # push images    
      # - name: docker push image ${{ env.REGISTRY }}/${{ env.AUTO_IMAGE_NAME }}:latest
      #   if: ${{ matrix.profile }} == 'auto'
      #   run: docker push ${{ env.REGISTRY }}/${{ env.AUTO_IMAGE_NAME }}:latest
       